# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/301_GroupProject/301_GroupProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/301_GroupProject/301_GroupProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/301_GroupProject/301_GroupProject/CMakeFiles /home/runner/work/301_GroupProject/301_GroupProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/301_GroupProject/301_GroupProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named multikernel_os

# Build rule for target.
multikernel_os: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multikernel_os
.PHONY : multikernel_os

# fast build rule for target.
multikernel_os/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/build
.PHONY : multikernel_os/fast

core_kernel.o: core_kernel.cpp.o
.PHONY : core_kernel.o

# target to build an object file
core_kernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/core_kernel.cpp.o
.PHONY : core_kernel.cpp.o

core_kernel.i: core_kernel.cpp.i
.PHONY : core_kernel.i

# target to preprocess a source file
core_kernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/core_kernel.cpp.i
.PHONY : core_kernel.cpp.i

core_kernel.s: core_kernel.cpp.s
.PHONY : core_kernel.s

# target to generate assembly for a file
core_kernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/core_kernel.cpp.s
.PHONY : core_kernel.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/main.cpp.s
.PHONY : main.cpp.s

multikernel_system.o: multikernel_system.cpp.o
.PHONY : multikernel_system.o

# target to build an object file
multikernel_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/multikernel_system.cpp.o
.PHONY : multikernel_system.cpp.o

multikernel_system.i: multikernel_system.cpp.i
.PHONY : multikernel_system.i

# target to preprocess a source file
multikernel_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/multikernel_system.cpp.i
.PHONY : multikernel_system.cpp.i

multikernel_system.s: multikernel_system.cpp.s
.PHONY : multikernel_system.s

# target to generate assembly for a file
multikernel_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multikernel_os.dir/build.make CMakeFiles/multikernel_os.dir/multikernel_system.cpp.s
.PHONY : multikernel_system.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... multikernel_os"
	@echo "... core_kernel.o"
	@echo "... core_kernel.i"
	@echo "... core_kernel.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... multikernel_system.o"
	@echo "... multikernel_system.i"
	@echo "... multikernel_system.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

